import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    margin: 0,
    paddingBottom: 80, // space for cart bar
    backgroundColor: "#efefefff",
  },
  image: {
    width: "100%",
    height: 250,
    resizeMode: "cover",
  },
  detailCard: {
    backgroundColor: "#efefefff",
    borderRadius: 12,
    margin: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000000ff",
    marginBottom: 8,
  },
  description: {
    fontSize: 14,
    color: "#353535ff",
    marginTop: 6,
    lineHeight: 20,
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  price: { fontSize: 16, fontWeight: "bold", marginRight: 10 },
  originalPrice: { color: "#5d5d5dff", textDecorationLine: "line-through" },
  salePrice: { color: "#09b71dff", fontWeight: "bold", fontSize: 18 },

  badgeContainer: { flexDirection: "row", marginVertical: 10 },
  badge: {
    backgroundColor: "#3d9105ff",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginRight: 8,
  },
  badgeText: { color: "#fff", fontSize: 12, fontWeight: "600" },

  cartActionContainer: { marginTop: 15, alignItems: "center" },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#006b3d",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 8,
  },
  addBtnText: { color: "#ffffffff", marginLeft: 6, fontSize: 14, fontWeight: "600" },
  qtySelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#efefefff",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderColor: "#006b3d",
    borderWidth: 1.5,
  },
  qtyText: { color: "#000000ff", marginHorizontal: 12, fontSize: 16, fontWeight: "600" },

  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000ff",
    marginTop: 20,
    marginBottom: 10,
  },

  // ✅ Sticky Cart Bar
  cartBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#ffffffff",
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#ffffffff",
    shadowColor: "#090b09ff",
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  cartBarText: {
    color: "#000000ff",
    fontSize: 14,
    fontWeight: "600",
  },
  cartBarButton: {
    backgroundColor: "#006b3d",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  cartBarButtonText: {
    color: "#fefefeff",
    fontWeight: "bold",
    fontSize: 14,
  },
  ribbonContainer: {
    position: "absolute",
    top: 6,
    left: 6,
    backgroundColor: "#c8102e",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  ribbonText: {
    fontSize: 10,
    color: "#ffffffff",
    fontWeight: "bold",
  },
});
